### ISSUE TITLE
Unknown command line argument '-skip-functions=f'.

### ISSUE THREAD

**Issue by arnab-security** [davidtr1037/chopper#26]
I have followed the commands to install SVF, DG and KLEE. But when I have tried the example, I am getting the following problem.

Unknown command line argument '-skip-functions=f'.

**Comment by davidtr1037** [comment]
Can you send me your command line? Did you compile the master branch?

**Comment by arnab-security** [comment]
I have followed the commands in the README for installing and running.
klee -libc=klee -search=dfs -skip-functions=f main.bc

Indeed I had the official Klee earlier but I have removed both klee and klee_uclibc now. I have used your klee_uclibc link but I don't see any klee link. So I used the official klee link to install klee again. Do you have a separate klee that I am supposed to use?

**Comment by arnab-security** [comment]
I think that I am supposed to use the chopper as klee. But in that case, I am getting a new error when I enter make.
In file included from /chopper/lib/Analysis/ReachabilityAnalysis.cpp:16:0:
 /chopper/include/klee/Internal/Analysis/AAPass.h:4:41: fatal error: MemoryModel/PointerAnalysis.h: No such file or directory. compilation terminated.

**Comment by davidtr1037** [comment]
Could you send me your configuration line (CMake) for chopper?

**Comment by arnab-security** [comment]
CXXFLAGS="-fno-rtti" cmake \
> -DENABLE_SOLVER_STP=ON \
> -DENABLE_POSIX_RUNTIME=ON \
> -DENABLE_KLEE_UCLIBC=ON \
> -DKLEE_UCLIBC_PATH=../../klee-uclibc/ \
> -DLLVM_CONFIG_BINARY=../../llvm-project/release/bin/llvm-config \
> -DENABLE_UNIT_TESTS=OFF \
> -DKLEE_RUNTIME_BUILD_TYPE=Release+Asserts \
> -DENABLE_SYSTEM_TESTS=ON \
> -DSVF_ROOT_DIR=../../SVF/ \
> -DDG_ROOT_DIR=../../dg/ \
> ..

**Comment by phan123123** [comment]
Hello, i got the same issue. Can anyone help me?
